# Question 3

In [1]:
import numpy as np
from numpy import linalg as LA

In [2]:
A = np.array([[3,3],[4,4],[0,6],[0,8]])

# CGS

In [3]:
#CGS
def cgs(A):
    m,n=A.shape
    Q=np.zeros((m,n))
    R=np.zeros((n,n))
    V=np.zeros((m,n))
    for j in range(0,n):
        V[:,j]=A[:,j]
        for i in range(0,j):
            R[i,j]=np.dot(Q[:,i].T,V[:,j])
            V[:,j]=V[:,j]-R[i,j]*Q[:,i]
        R[j,j]=LA.norm(V[:,j],2)
        Q[:,j]=V[:,j]/R[j,j]  
    return(Q,R)

In [4]:
Q_C,R_C=cgs(A)

### Output of CGS

In [5]:
print("Q")
print(Q_C)
print("")
print("R")
print(R_C)

Q
[[0.6 0. ]
 [0.8 0. ]
 [0.  0.6]
 [0.  0.8]]

R
[[ 5.  5.]
 [ 0. 10.]]


## MGS

In [6]:
#MGS
def mgs(A):
    m,n=A.shape
    Q=np.zeros((m,n))
    R=np.zeros((n,n))
    V=np.zeros((m,n))
    for i in range(0,n):
        V[:,i]=A[:,i]    
    for i in range(0,n):
        R[i,i]=LA.norm(V[:,i],2)
        Q[:,i]=V[:,i]/R[i,i]
        for j in range(i+1,n):
            R[i,j]=np.dot(Q[:,i].T,V[:,j])
            V[:,j]=V[:,j]-R[i,j]*Q[:,i]
    return(Q,R)

In [7]:
Q_M,R_M=mgs(A)

### Output of MGS

In [8]:
print("Q")
print(Q_M)
print("")
print("R")
print(R_M)

Q
[[0.6 0. ]
 [0.8 0. ]
 [0.  0.6]
 [0.  0.8]]

R
[[ 5.  5.]
 [ 0. 10.]]


# Question 4

In [9]:
from math import copysign, hypot

In [10]:
A2=np.array([[1,1],[1,2],[1,3]])

## Givens Rotation

In [11]:
def givens_rotation(A):
    m2,n2=A2.shape
    Q = np.identity(m2)
    R = np.copy(A)
    (rows, cols) = np.tril_indices(m2, -1, n2)
    for (row, col) in zip(rows, cols):
        if R[row, col] != 0:
            (c, s) = _givens_rotation_matrix(R[col, col], R[row, col])
            G = np.identity(m2)
            G[[col, row], [col, row]] = c
            G[row, col] = s
            G[col, row] = -s
            R = np.dot(G, R)
            Q = np.dot(Q, G.T)

    return (Q, R)


def _givens_rotation_matrix(a, b):
    r = hypot(a, b)
    c = a/r
    s = -b/r

    return (c, s)

In [12]:
Q_G,R_G=givens_rotation(A2)

### Output of Givens Rotation Method

In [13]:
print("Q")
print(Q_G)
print("")
print("R")
print(R_G)

Q
[[ 5.77350269e-01 -7.07106781e-01  4.08248290e-01]
 [ 5.77350269e-01 -1.16069829e-17 -8.16496581e-01]
 [ 5.77350269e-01  7.07106781e-01  4.08248290e-01]]

R
[[1.73205081 3.46410162]
 [0.         1.41421356]
 [0.         0.        ]]


## Householder Method

In [14]:
def column_convertor(x):
    x.shape = (1, x.shape[0])
    return x

def householder_logic(x):
    e1=np.zeros(x.shape[1])
    e1[0]=1
    v_temp=LA.norm(x,2)*e1
    if v_temp[0]<0:
        v_temp=-v_temp
    v=x+v_temp
    p=np.matmul(v.T,v)
    l=LA.norm(v,2)**2
    H=np.identity(x.shape[1])-2*(np.matmul(v.T,v)/(LA.norm(v,2)**2))
    return H



In [15]:
def householder_service(A):
    m,n = A.shape
    Q=np.identity(m)
    R=np.copy(A)
    for i in range(0,n):
        x=R[i:,i]
        x=column_convertor(x)
        H=householder_logic(x)
        Q_temp=np.identity(m)
        Q_temp[i:,i:]=H
        R=np.matmul(Q_temp, R)
        Q=np.matmul(Q, Q_temp)
    return (Q,R)

In [16]:
Q_H,R_H=householder_service(A2)

## Output of Householder Method

In [17]:
print("Q")
print(np.around(Q_H,4))
print("")
print("R")
print(np.around(R_H,4))

Q
[[-0.5774  0.7071  0.4082]
 [-0.5774 -0.     -0.8165]
 [-0.5774 -0.7071  0.4082]]

R
[[-1.7321 -3.4641]
 [-0.     -1.4142]
 [-0.     -0.    ]]
